name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    workingDirectory: TP_DOCKER_2/src
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          run:
          working-directory: TP_DOCKER_2/src
          run: npm install
          run: npm install
